name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main # Or your default branch, e.g., master

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pages: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          publish_dir: ./ # This assumes your index.html is at the root
          # If your site is in a subfolder like 'public' or 'dist', change './' to './public' or './dist'
